version = 1

# For files or folders that can not be annotated via comment headers, add them here

[[annotations]]
path = ".changeset/*"
SPDX-License-Identifier = "CC-BY-SA-4.0"
SPDX-FileCopyrightText = "Nordeck IT + Consulting GmbH"

[[annotations]]
path = "public/**"
SPDX-License-Identifier = "CC-BY-SA-4.0"
SPDX-FileCopyrightText = "Nordeck IT + Consulting GmbH"

[[annotations]]
path = "docs/**"
SPDX-License-Identifier = "CC-BY-SA-4.0"
SPDX-FileCopyrightText = "Nordeck IT + Consulting GmbH"

[[annotations]]
path = "src/locales/**"
SPDX-License-Identifier = "CC-BY-SA-4.0"
SPDX-FileCopyrightText = "Nordeck IT + Consulting GmbH"

[[annotations]]
path = "charts/**"
SPDX-License-Identifier = "AGPL-3.0-or-later"
SPDX-FileCopyrightText = "Nordeck IT + Consulting GmbH"

[[annotations]]
path = ".github/**"
SPDX-License-Identifier = "AGPL-3.0-or-later"
SPDX-FileCopyrightText = "Nordeck IT + Consulting GmbH"

[[annotations]]
path = "tsconfig.*.json"
SPDX-License-Identifier = "AGPL-3.0-or-later"
SPDX-FileCopyrightText = "Nordeck IT + Consulting GmbH"

[[annotations]]
path = "tsconfig.json"
SPDX-License-Identifier = "AGPL-3.0-or-later"
SPDX-FileCopyrightText = "Nordeck IT + Consulting GmbH"

[[annotations]]
path = "package.json"
SPDX-License-Identifier = "AGPL-3.0-or-later"
SPDX-FileCopyrightText = "Nordeck IT + Consulting GmbH"

[[annotations]]
path = ".husky/**"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = "Nordeck IT + Consulting GmbH"

[[annotations]]
path = "yarn.lock"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = "Nordeck IT + Consulting GmbH"
