apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.name" . }}-cm
  labels:
{{ include "app.labels" . | indent 4 }}
    app.kubernetes.io/component: csp-config
data:
  content-security-policy.conf: |
    {{ .Values.custom_csp_headers }}
