apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.name" . }}-od-cm
  labels:
{{ include "app.labels" . | indent 4 }}
    app.kubernetes.io/component: opendesk-config
data:
  {{- if .Values.opendesk_navigation }}
  navigation.json: |
{{ .Values.opendesk_navigation | indent 4 }}
  {{- end }}
  {{- if .Values.opendesk_silent }}
  silent.html: |
{{ .Values.opendesk_silent | indent 4 }}
  {{- end }}
