name: NeoBoard Standalone CI

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
  workflow_dispatch:
    inputs:
      neoboard_ref:
        description: 'NeoBoard Git ref to check out'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      ARGOCD_SHA: ''
      DOCKER_IMAGE: ghcr.io/nordeck/matrix-neoboard-standalone
      REACT_APP_REACT_SDK_VERSION: 'unset'
      REACT_APP_REACT_SDK_REVISION: 'unset'
    outputs:
      ARGOCD_TAG: ${{ steps.argocd-sha.outputs.ARGOCD_TAG }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          repository: nordeck/matrix-neoboard
          path: matrix-neoboard
          ref: ${{ github.events.inputs.neoboard_ref }}
          # required for changesets
          fetch-depth: '0'
          # don't persist the credentials so the changesets action doesn't use the
          # github actions token but the git token provided via environment variable
          persist-credentials: false

      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          path: matrix-neoboard-standalone
          # required for changesets
          fetch-depth: '0'
          # don't persist the credentials so the changesets action doesn't use the
          # github actions token but the git token provided via environment variable
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: 'matrix-neoboard-standalone/package.json'
          cache: 'yarn'
          cache-dependency-path: |
            matrix-neoboard-standalone/yarn.lock
            matrix-neoboard/yarn.lock

      - name: yarn install neoboard
        working-directory: ./matrix-neoboard/
        run: yarn install --frozen-lockfile

      - name: yarn install neoboard standalone
        working-directory: ./matrix-neoboard-standalone/
        run: yarn install --frozen-lockfile

      - name: depcheck
        working-directory: ./matrix-neoboard-standalone/
        run: yarn depcheck

      - name: prettier:check
        working-directory: ./matrix-neoboard-standalone/
        run: yarn prettier:check

      - name: Check Linting Rules
        working-directory: ./matrix-neoboard-standalone/
        run: yarn lint

      - name: type checking and declarations
        working-directory: ./matrix-neoboard-standalone/
        run: yarn tsc

      - name: Check Translations
        working-directory: ./matrix-neoboard-standalone/
        run: yarn translate --ci --dry-run

      - name: test
        working-directory: ./matrix-neoboard-standalone/
        run: yarn run test:all

      - name: build
        working-directory: ./matrix-neoboard-standalone/
        run: yarn build && yarn version:info

      - name: generate disclaimer
        working-directory: ./matrix-neoboard-standalone/
        run: yarn generate-disclaimer

      - name: Login to ghcr.io
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: get argo-cd type of sha
        id: argocd-sha
        run: |
          COMMIT_SHA=${{ github.sha }}
          if [[ '${{ github.event_name }}' == 'pull_request' ]]
          then
            COMMIT_SHA=${{ github.event.pull_request.head.sha }}
          fi
          ARGOCD_TAG=argo-$(echo $COMMIT_SHA | cut -c1-8)
          echo "ARGOCD_TAG=$ARGOCD_TAG" >> $GITHUB_ENV
          echo "ARGOCD_TAG=$ARGOCD_TAG" >> "$GITHUB_OUTPUT"

      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5
        env:
          DOCKER_METADATA_PR_HEAD_SHA: true
        with:
          images: ${{ env.DOCKER_IMAGE }}
          labels: |
            org.opencontainers.image.title=NeoBoard standalone
            org.opencontainers.image.description=Standalone version of NeoBoard: A whiteboard widget for Matrix
            org.opencontainers.image.vendor=Nordeck IT + Consulting GmbH
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,prefix=
            type=raw,value=${{ env.ARGOCD_TAG }}

      # Read the created files into variables
      - name: Read version and revision to be used by docker
        id: read_version
        run: |
          REACT_APP_REACT_SDK_VERSION=$(cat ./matrix-neoboard-standalone/build/sdk_version)
          REACT_APP_REACT_SDK_REVISION=$(cat ./matrix-neoboard-standalone/build/sdk_revision)
          echo "REACT_APP_REACT_SDK_VERSION=$REACT_APP_REACT_SDK_VERSION" >> $GITHUB_ENV
          echo "REACT_APP_REACT_SDK_REVISION=$REACT_APP_REACT_SDK_REVISION" >> $GITHUB_ENV
          echo $GITHUB_ENV

      - name: Build and push
        id: build_and_push
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          push: ${{ github.event_name == 'push' && ( github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/') ) || github.event_name == 'pull_request' && secrets.GH_APP_OS_APP_ID != '' || github.event_name == 'workflow_dispatch' }}
          context: ./matrix-neoboard-standalone/
          build-contexts: |
            root=./
          tags: |
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64,linux/s390x
          sbom: true
          provenance: true
          build-args: |
            REACT_APP_VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
            REACT_APP_REVISION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}
            REACT_APP_REACT_SDK_VERSION=${{ env.REACT_APP_REACT_SDK_VERSION }}
            REACT_APP_REACT_SDK_REVISION=${{ env.REACT_APP_REACT_SDK_REVISION }}
            REACT_APP_EMBEDDED=true

      - name: Run Trivy to get an SBOM report of the container
        if: ${{ success() && steps.build_and_push.outputs.digest }}
        env:
          IMAGE_REF: ${{ env.DOCKER_IMAGE }}@${{ steps.build_and_push.outputs.digest }}
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
        with:
          scan-type: 'image'
          scanners: 'license'
          format: 'spdx-json'
          output: 'sbom.spdx.json'
          image-ref: ${{ env.IMAGE_REF }}
          github-pat: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload SBOM report as a build artifact
        if: ${{ success() && steps.build_and_push.outputs.digest }}
        uses: actions/upload-artifact@v4
        with:
          name: sbom-spdx-report
          path: 'sbom.spdx.json'
          retention-days: 30

      - name: Generate GitHub token
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # @v2.1.0
        with:
          app_id: ${{ secrets.GH_APP_OS_APP_ID }}
          private_key: ${{ secrets.GH_APP_OS_PRIVATE_KEY }}

      - name: Create Release Pull Request or Publish Packages
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: changesets/action@e0145edc7d9d8679003495b11f87bd8ef63c0cba # v1.5.3
        with:
          publish: yarn changeset tag
          cwd: ./matrix-neoboard-standalone/
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}

  helm-lint-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0 # need main branch to diff against
      - name: Set up Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.14'
          check-latest: true
      - name: Set up chart-testing
        uses: helm/chart-testing-action@6ec842c01de15ebb84c8627d2744a0c2f2755c9f # v2.8.0
      - name: Check if Helm charts updated (run chart-testing list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi
      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        # --validate-maintainers is disabled because it tries to resolve the name as GitHub user
        run: ct lint --validate-maintainers=false --target-branch ${{ github.event.repository.default_branch }}
      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@92086f6be054225fa813e0a4b13787fc9088faab # v1.13.0
      - name: Prepare k8s cluster
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          kubectl create namespace neoboard-standalone
          kubectl create secret docker-registry neoboard-standalone --docker-server=https://ghcr.io --docker-username="$USERNAME" --docker-password="$GITHUB_TOKEN" --namespace=neoboard-standalone
      # This is done since we set DOCKER_METADATA_PR_HEAD_SHA to true in the build job. This makes us use the PR SHA as the tag
      - name: Set short github sha from github.sha
        run: echo "SHORT_SHA=`echo ${PR_SHA:-$GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
        env:
          PR_SHA: ${{ github.event.pull_request.head.sha }}
          GITHUB_SHA: ${{ github.sha }}
      - name: Run chart-testing (install)
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          echo "Running chart-testing install for ${{ env.SHORT_SHA }}"
          ct install --config=".github/k8s_config.yaml" --target-branch ${{ github.event.repository.default_branch }} --helm-extra-set-args="--set=imagePullSecrets[0].name=neoboard-standalone --set=image.tag=${{ env.SHORT_SHA }}"

  create-chart-tag:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: build
    env:
      REPOSITORY: ghcr.io/nordeck/charts
      CHART_NAME: matrix-neoboard-standalone
    steps:
      - name: Generate GitHub token
        id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # @v2.1.0
        with:
          app_id: ${{ secrets.GH_APP_OS_APP_ID }}
          private_key: ${{ secrets.GH_APP_OS_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Read chart version
        id: vars
        run: |
          CHART_VERSION=$(grep '^version:' ./charts/$CHART_NAME/Chart.yaml | awk '{print $2}' | tr -d '"')

          echo "$CHART_VERSION"

          if [[ -n "$CHART_VERSION" ]]; then
            echo "chart_version=$CHART_VERSION" >> $GITHUB_OUTPUT
          else
            echo "Empty chart version"
            exit 1
          fi

      - name: Check if helm chart exists in OCI registry
        id: chart-exists
        env:
          CHART_VERSION: ${{ steps.vars.outputs.chart_version }}
        run: |
          # don't fail the action if the 'helm show chart' call exits with 1.
          # We handle the error manually. Similar to 'buildContainers' in Matrix Widget Toolkit.
          set +e

          OUTPUT=$(helm show chart oci://$REPOSITORY/$CHART_NAME --version $CHART_VERSION 2>&1)
          RESULT=$([[ "$?" == 0 ]] && echo "true" || echo "false")

          echo "$OUTPUT"

          if [[ $RESULT == "true" ]]; then
            echo "Chart $CHART_NAME with version $CHART_VERSION already exists."
          else
            if [[ $OUTPUT != "Error: failed to perform \"FetchReference\" on source: $REPOSITORY/$CHART_NAME:$CHART_VERSION: not found" ]]; then
              echo "Unexpected error"
              exit 1
            fi
          fi

          echo "result=$RESULT" >> $GITHUB_OUTPUT

      - name: Create tag
        if: ${{ steps.chart-exists.outputs.result == 'false' }}
        env:
          CHART_VERSION: ${{ steps.vars.outputs.chart_version }}
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          TAG="@nordeck/helm-$CHART_NAME-$CHART_VERSION"

          git tag $TAG
          git push origin $TAG

  deploy:
    if: ${{ contains(fromJSON('["push", "workflow_dispatch"]'), github.event_name) && github.ref == 'refs/heads/main' }}
    name: Deploy to Dev
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [build, helm-lint-test]
    steps:
      # Clone repo to get the helm charts
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Checkout valhalla for values
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          ref: dev
          sparse-checkout: |
            /cluster/neotoolsuite-dev/matrix-neoboard-standalone/values.dev.yaml
            /cluster/neotoolsuite-dev/matrix-neoboard-standalone/values.infinite-canvas.yaml
          sparse-checkout-cone-mode: false
          repository: nordeck/valhalla
          token: ${{ secrets.PACKAGE_TOKEN }}
          path: valhalla
          persist-credentials: false

      - name: Set up Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1

      - name: Create Kubeconfig
        run: |
          # Extract the base64 encoded config data and write this to the KUBECONFIG
          echo "${{ secrets.KUBECONFIG_NEOTOOLSUITE_DEV }}" | base64 -d > /tmp/config
          chmod 600 /tmp/config
          echo "KUBECONFIG=/tmp/config" >> $GITHUB_ENV

      - name: deploy k8s to cluster
        run: |
          helm upgrade --rollback-on-failure --install matrix-neoboard-standalone ./charts/matrix-neoboard-standalone -f ./valhalla/cluster/neotoolsuite-dev/matrix-neoboard-standalone/values.dev.yaml -n matrix --set image.tag=${{ needs.build.outputs.ARGOCD_TAG }}

      # inifinite canvas
      - name: deploy k8s to cluster
        run: |
          helm upgrade --rollback-on-failure --install matrix-neoboard-standalone-infinite-canvas ./charts/matrix-neoboard-standalone -f ./valhalla/cluster/neotoolsuite-dev/matrix-neoboard-standalone/values.infinite-canvas.yaml -n matrix --set image.tag=${{ needs.build.outputs.ARGOCD_TAG }}
