name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      DOCKER_IMAGE: ghcr.io/nordeck/matrix-neoboard-standalone
    outputs:
      docker-tag: ${{ steps.meta.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: nordeck/matrix-neoboard
          path: matrix-neoboard
          # required for changesets
          fetch-depth: '0'
          # don't persist the credentials so the changesets action doesn't use the
          # github actions token but the git token provided via environment variable
          persist-credentials: false

      - uses: actions/checkout@v4
        with:
          path: matrix-neoboard-standalone
          # required for changesets
          fetch-depth: '0'
          # don't persist the credentials so the changesets action doesn't use the
          # github actions token but the git token provided via environment variable
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: |
            matrix-neoboard-standalone/yarn.lock
            matrix-neoboard/yarn.lock

      - name: yarn install neoboard
        working-directory: ./matrix-neoboard/
        run: yarn install --frozen-lockfile

      - name: yarn install neoboard standalone
        working-directory: ./matrix-neoboard-standalone/
        run: yarn install --frozen-lockfile

      - name: depcheck
        working-directory: ./matrix-neoboard-standalone/
        run: yarn depcheck

      - name: prettier:check
        working-directory: ./matrix-neoboard-standalone/
        run: yarn prettier:check

      - name: Check Linting Rules
        working-directory: ./matrix-neoboard-standalone/
        run: yarn lint

      - name: type checking and declarations
        working-directory: ./matrix-neoboard-standalone/
        run: yarn tsc

      - name: Check Translations
        working-directory: ./matrix-neoboard-standalone/
        run: yarn translate --fail-on-update

      - name: test
        working-directory: ./matrix-neoboard-standalone/
        run: yarn run test:all

      - name: build
        working-directory: ./matrix-neoboard-standalone/
        run: yarn build

      - name: generate disclaimer
        working-directory: ./matrix-neoboard-standalone/
        run: yarn generate-disclaimer

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        env:
          DOCKER_METADATA_PR_HEAD_SHA: true
        with:
          images: ${{ env.DOCKER_IMAGE }}
          labels: |
            org.opencontainers.image.title=NeoBoard standalone
            org.opencontainers.image.description=Standalone version of NeoBoard: A whiteboard widget for Matrix
            org.opencontainers.image.vendor=Nordeck IT + Consulting GmbH
          tags: |
            type=raw,value=latest
            type=sha,prefix=

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'pull_request' && secrets.GH_APP_OS_APP_ID != '' }}
          context: ./matrix-neoboard-standalone/
          tags: |
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64,linux/s390x
          sbom: true
          provenance: true
          build-args: |
            REACT_APP_VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
            REACT_APP_REVISION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}

  deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    name: Deploy to Dev
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: build
    steps:
      # Clone repot to get the helm charts
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          persist-credentials: false

      - name: Create Kubeconfig
        run: |
          # Extract the base64 encoded config data and write this to the KUBECONFIG
          echo "${{ secrets.KUBECONFIG_DEV }}" | base64 -d > /tmp/config
          chmod 600 /tmp/config

          echo "KUBECONFIG=/tmp/config" >> $GITHUB_ENV

      - name: deploy k8s to cluster
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG_RANCHER_DEV_DEMO }}
        with:
          args: |
            helm upgrade --install matrix-neoboard-standalone ./charts/matrix-neoboard-standalone -f ./charts/matrix-neoboard-standalone/values.yaml  -n matrix

      - name: restart rollout
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG_RANCHER_DEV_DEMO }}
        with:
          args: |
            kubectl rollout restart deployment matrix-neoboard-standalone -n matrix
