name: Deploy to Demo

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Input the image tag to deploy'
        required: true

jobs:
  deploy-demo:
    name: Deploy to Demo
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # Clone repo to get the helm charts
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Checkout valhalla for values
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          ref: dev
          sparse-checkout: |
            /cluster/neotoolsuite-demo/matrix-neoboard-standalone/values.demo.yaml
          sparse-checkout-cone-mode: false
          repository: nordeck/valhalla
          token: ${{ secrets.PACKAGE_TOKEN }}
          path: valhalla
          persist-credentials: false

      - name: Set up Helm
        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4.3.0

      - name: Create Kubeconfig
        run: |
          # Extract the base64 encoded config data and write this to the KUBECONFIG
          echo "${{ secrets.KUBECONFIG_NEOTOOLSUITE_DEMO }}" | base64 -d > /tmp/config
          chmod 600 /tmp/config
          echo "KUBECONFIG=/tmp/config" >> $GITHUB_ENV

      - name: deploy k8s to cluster
        run: |
          helm upgrade --install matrix-neoboard-standalone ./charts/matrix-neoboard-standalone -f ./valhalla/cluster/neotoolsuite-demo/matrix-neoboard-standalone/values.demo.yaml -n matrix --set image.tag=${{ github.event.inputs.image_tag }}

      - name: restart rollout
        run: |
          kubectl rollout restart deployment matrix-neoboard-standalone -n matrix
