name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      # Check out the dev env repo
      - uses: actions/checkout@v4
        with:
          repository: 'nordeck/opendesk-widgets-docker-compose'
          token: ${{ secrets.PACKAGE_TOKEN }}
          path: opendesk-widgets-docker-compose
          submodules: true
      # Update the /etc/hosts of the runner to point to the dev env
      - name: Set the required /etc/hosts entries
        run: |
          echo "127.0.0.1 element.matrix.internal matrix.internal mas.matrix.internal" | sudo tee -a /etc/hosts
          echo "127.0.0.1 neodatefix.matrix.internal neochoice.matrix.internal neoboard.matrix.internal meetings-bot.matrix.internal" | sudo tee -a /etc/hosts
          echo "127.0.0.1 meet.matrix.internal uvs.matrix.internal" | sudo tee -a /etc/hosts
          echo "127.0.0.1 livekit.matrix.internal livekit-jwt.matrix.internal turn.matrix.internal" | sudo tee -a /etc/hosts

      - uses: actions/checkout@v4
        with:
          repository: nordeck/matrix-neoboard
          path: matrix-neoboard
          ref: ${{ github.events.inputs.neoboard_ref }}

      - uses: actions/checkout@v4
        with:
          path: matrix-neoboard-standalone

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'matrix-neoboard-standalone/package.json'
          cache: 'yarn'
          cache-dependency-path: |
            matrix-neoboard-standalone/yarn.lock
            matrix-neoboard/yarn.lock

      - name: yarn install neoboard
        working-directory: ./matrix-neoboard/
        run: yarn install --frozen-lockfile

      - name: yarn install neoboard standalone
        working-directory: ./matrix-neoboard-standalone/
        run: yarn install --frozen-lockfile

      - name: Install Playwright Browsers
        working-directory: ./matrix-neoboard-standalone/
        run: yarn playwright install --with-deps
      - name: Start dev env
        working-directory: ./opendesk-widgets-docker-compose/
        run: |
          docker compose -f compose.mas.yaml --env-file nordeck.env up -d
          #docker compose -f compose.mas.yaml --env-file nordeck.env exec synapse /bin/sh -c /scripts/start.sh
          #docker compose -f compose.mas.yaml --env-file nordeck.env restart meetings-bot uvs
          # wait until matrix.internal is up by checking /_matrix/client/versions
          # print the synapse logs to the console for debugging
          docker compose -f compose.mas.yaml --env-file nordeck.env logs synapse
          while ! curl -k -s -o /dev/null -w "%{http_code}" https://matrix.internal/_matrix/client/versions | grep -q 200; do
            echo "Waiting for matrix.internal to be up..."
            sleep 5
          done
          # Create the test user using the mas cli
          docker compose -f compose.mas.yaml --env-file nordeck.env exec mas mas-cli manage register-user --yes --password pWPv3OMxEnPkLtvQ2g6L2qWTcY0UAlmHLljwDK0ZoiQZRvJ3nR2dRCKENGvDiadL --email test@example.com --no-admin --display-name test --ignore-password-complexity test
          docker compose -f compose.mas.yaml --env-file nordeck.env exec mas mas-cli manage verify-email test test@example.com
          docker compose -f compose.mas.yaml --env-file nordeck.env exec mas mas-cli manage provision-all-users
      - name: Run Playwright tests
        working-directory: ./matrix-neoboard-standalone/
        run: yarn playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: ./matrix-neoboard-standalone/playwright-report/
          retention-days: 30
