name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      # Check out the dev env repo
      - uses: actions/checkout@v4
        with:
          repository: 'nordeck/opendesk-widgets-docker-compose'
      # Update the /etc/hosts of the runner to point to the dev env
      - name: Set the required /etc/hosts entries
        run: |
          echo "127.0.0.1 element.matrix.internal matrix.internal mas.matrix.internal" | sudo tee -a /etc/hosts
          echo "127.0.0.1 neodatefix.matrix.internal neochoice.matrix.internal neoboard.matrix.internal meetings-bot.matrix.internal" | sudo tee -a /etc/hosts
          echo "127.0.0.1 meet.matrix.internal uvs.matrix.internal" | sudo tee -a /etc/hosts
          echo "127.0.0.1 livekit.matrix.internal livekit-jwt.matrix.internal turn.matrix.internal" | sudo tee -a /etc/hosts
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install -g yarn && yarn
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
      - name: Run Playwright tests
        run: yarn playwright test
      - name: Start dev env
        run: |
          docker compose -f compose.mas.yaml --env-file nordeck.env up -d
          docker compose -f compose.mas.yaml --env-file nordeck.env exec synapse /bin/sh -c /scripts/start.sh
          docker compose -f compose.mas.yaml --env-file nordeck.env restart meetings-bot uvs
          # Create the test user using the mas cli
          docker compose -f compose.mas.yaml --env-file nordeck.env exec mas /bin/sh -c mas-cli manage register-user --yes --username test --password pWPv3OMxEnPkLtvQ2g6L2qWTcY0UAlmHLljwDK0ZoiQZRvJ3nR2dRCKENGvDiadL --email test@example.com --no-admin --display-name test --ignore-password-complexity
          docker compose -f compose.mas.yaml --env-file nordeck.env exec mas /bin/sh -c mas-cli manage verify-email test test@example.com
          docker compose -f compose.mas.yaml --env-file nordeck.env exec mas /bin/sh -c mas-cli manage provision-all-users
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
